const MYSQL_SCHEMA = "school";
const MYSQL_TABLENAME_STUDENTS = "tbl_students";
const MYSQL_STUDENTS_COL_TEACHERSID = "teachers_id";
const MYSQL_TABLENAME_TEACHERS = "tbl_teachers";

module.exports = {
  SCHEMA: MYSQL_SCHEMA,
  TABLE_STUDENTS: MYSQL_TABLENAME_STUDENTS,
  TABLE_TEACHERS: MYSQL_TABLENAME_TEACHERS,
  STUDENTS_COL_TEACHERS_ID: MYSQL_STUDENTS_COL_TEACHERSID
};
