const MYSQL_TABLENAME_STUDENTS = "tbl_students";
const MYSQL_TABLENAME_TEACHERS = "tbl_teachers";
const MYSQL_TABLENAME_TEACHERS_STUDENTS = "tbl_teachers_students";

module.exports = {
  TABLE_STUDENTS: MYSQL_TABLENAME_STUDENTS,
  TABLE_TEACHERS: MYSQL_TABLENAME_TEACHERS,
  TABLE_TEACHERS_STUDENTS: MYSQL_TABLENAME_TEACHERS_STUDENTS
};
